/**
 * Extracts the prototype's real seed data and emits SQL.
 *
 * The data is read from the FULLY LOADED page, not from one <script> block.
 *
 * An earlier version of this script evaluated only the block that declares
 * DATA, and silently produced an incomplete seed: a later block
 * (prototype.html:6392) enriches every candidate with gender,
 * emailVerified, mobileVerified, activity and recruiter comments. None of
 * that was captured, so the "✓ Verified" badges and every recruiter note
 * were missing from the database — while all the row counts still looked
 * correct, which is exactly why it went unnoticed.
 *
 * Running the real page means whatever the prototype ACTUALLY has at
 * runtime is what gets migrated, including enrichment applied by any of
 * its 117 script blocks.
 *
 * Requires the baseline server:  npx http-server baseline -p 4321
 */
import { writeFileSync } from 'node:fs';
import { chromium } from 'playwright';

const BASE = process.env.TL_BASELINE_URL || 'http://127.0.0.1:4321/prototype.html';

const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto(BASE, { waitUntil: 'load' });
await page.waitForTimeout(1200);
await page.evaluate(() => { location.hash = '#/jobs'; });
await page.waitForTimeout(600);

const DATA = await page.evaluate(() => JSON.parse(JSON.stringify({
  companies: DATA.companies,
  jobs: DATA.jobs,
  candidates: DATA.candidates,
  recruiters: DATA.recruiters,
  clients: DATA.clients,
  admin: DATA.admin,
  interviews: DATA.interviews,
  whatsappTemplates: DATA.whatsappTemplates,
})));
await browser.close();

// ---------- helpers ----------
const q    = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const num  = (v) => (v === null || v === undefined || v === '' || Number.isNaN(Number(v)) ? 'null' : Number(v));
const bool = (v) => (v ? 'true' : 'false');
const arr  = (v) => (!Array.isArray(v) || !v.length ? `'{}'` : `ARRAY[${v.map(q).join(',')}]::text[]`);
const json = (v) => `'${JSON.stringify(v ?? []).replace(/'/g, "''")}'::jsonb`;

const expYears = (s) => {
  if (!s) return null;
  const m = String(s).match(/(\d+(?:\.\d+)?)/);
  return m ? Number(m[1]) : null;
};
const daysAgo = (s) => {
  if (!s) return 0;
  const t = String(s).toLowerCase();
  if (t.includes('today')) return 0;
  const m = t.match(/(\d+)\s*(day|week|month)/);
  if (!m) return 0;
  const n = Number(m[1]);
  return m[2] === 'week' ? n * 7 : m[2] === 'month' ? n * 30 : n;
};

const out = [];
const P = (s) => out.push(s);

P(`-- =====================================================================
-- TeamLink seed — GENERATED by tools/extract-seed.mjs from the RUNNING
-- prototype. Do not hand-edit; re-run the extractor.
--
-- This is the prototype's own demo content, loaded so every screen has the
-- same data it had before. It is seed, not a runtime dependency: the
-- application reads these rows from Postgres and works just as well with
-- an empty database.
-- =====================================================================

-- RLS is FORCEd on every table, so seeding runs with privileges that
-- bypass it (migrations connect as a superuser; the API never does).
select set_config('app.service', 'on', false);
`);

P(`-- companies (${DATA.companies.length})`);
for (const c of DATA.companies) {
  P(`insert into companies (id,name,industry,hq,founded,size_label,color1,color2,about) values (`
    + `${q(c.id)},${q(c.name)},${q(c.industry)},${q(c.hq)},${num(c.founded)},${q(c.size)},`
    + `${q(c.color1)},${q(c.color2)},${q(c.about)});`);
}

P(`\n-- users are created by api/src/scripts/seed-auth.js (bcrypt, never plain text)`);

P(`\n-- recruiters (${DATA.recruiters.length})`);
for (const r of DATA.recruiters) {
  P(`insert into recruiters (id,name,email,company_id,title,initials) values (`
    + `${q(r.id)},${q(r.name)},${q(r.email)},${q(r.companyId)},${q(r.title)},${q(r.initials)});`);
}

P(`\n-- client users (${DATA.clients.length})`);
for (const c of DATA.clients) {
  P(`insert into client_users (id,name,email,company_id,title,initials) values (`
    + `${q(c.id)},${q(c.name)},${q(c.email)},${q(c.companyId)},${q(c.title)},${q(c.initials)});`);
}

const a = DATA.admin;
P(`\n-- admin`);
P(`insert into admins (id,name,email,title,initials) values (`
  + `${q(a.id)},${q(a.name)},${q(a.email)},${q(a.title)},${q(a.initials)});`);

P(`\n-- jobs (${DATA.jobs.length}) — ids preserved verbatim (requirement 6)`);
for (const j of DATA.jobs) {
  const d = j.postedDaysAgo != null ? Number(j.postedDaysAgo) : daysAgo(j.posted);
  P(`insert into jobs (id,title,company_id,location,mode,exp_label,pay_label,salary_min,salary_max,`
    + `employment_type,posting_kind,department,education,easy_apply,featured,status,paused,archived,`
    + `skills,description,responsibilities,requirements,published_at) values (`
    + `${q(j.id)},${q(j.title)},${q(j.companyId)},${q(j.location)},${q(j.mode)},${q(j.exp)},${q(j.pay)},`
    + `${num(j.salaryMin)},${num(j.salaryMax)},${q(j.type)},${q(j.postingKind || 'job')},`
    + `${q(j.department)},${q(j.education)},${bool(j.easyApply)},${bool(j.featured)},`
    + `${q(j.status === 'open' ? 'open' : j.status)},${bool(j.paused)},${bool(j.archived)},`
    + `${arr(j.skills)},${q(j.desc)},${arr(j.responsibilities)},${arr(j.requirements)},`
    + `now() - interval '${d} days');`);
}

P(`\n-- candidates (${DATA.candidates.length})`);
P(`-- NOTE: appliedJobId / stage / matchScore are NOT columns here. They`);
P(`--       become a primary application row below (DATA-MAPPING §3.1).`);
for (const c of DATA.candidates) {
  P(`insert into candidates (id,name,email,phone,location,gender,title,exp,exp_years,ctc,expected_ctc,`
    + `notice_period,current_company,previous_companies,career_goal,preferred_role,preferred_location,`
    + `candidate_type,preferred_work_modes,skills,technical_skills,education,summary,certifications,`
    + `languages,projects,linkedin,github,portfolio,resume_file,ai_interview_score,qualified,`
    + `email_verified,mobile_verified,sms_verified,whatsapp_opt_in,days_silent,follow_up_sent,`
    + `is_private,profile_active_days_ago,profile_updated_days_ago) values (`
    + `${q(c.id)},${q(c.name)},${q(c.email)},${q(c.phone)},${q(c.location)},${q(c.gender)},${q(c.title)},`
    + `${q(c.exp)},${num(expYears(c.exp))},${q(c.ctc)},${num(c.expectedCtc)},${q(c.noticePeriod)},`
    + `${q(c.currentCompany)},${arr(c.previousCompanies)},${q(c.careerGoal)},${q(c.preferredRole)},`
    + `${q(c.preferredLocation)},${q(c.candidateType)},${arr(c.preferredWorkModes)},${arr(c.skills)},`
    + `${arr(c.technicalSkills)},${q(c.education)},${q(c.summary)},${arr(c.certifications)},`
    + `${arr(c.languages)},${json(c.projects)},${q(c.linkedin)},${q(c.github)},${q(c.portfolio)},`
    + `${q(c.resumeFile)},${num(c.aiInterviewScore)},${c.qualified == null ? 'null' : bool(c.qualified)},`
    + `${bool(c.emailVerified)},${bool(c.mobileVerified)},${bool(c.smsVerified)},${bool(c.whatsappOptIn)},`
    + `${num(c.daysSilent)},${bool(c.followUpSent)},${bool(c.isPrivate)},`
    + `${num(c.profileActiveDaysAgo)},${num(c.profileUpdatedDaysAgo)});`);
}

P(`\n-- primary applications — each candidate's seeded pipeline entry becomes a`);
P(`-- real row, which is the fix for the prototype's double-modelled applications.`);
let n = 0;
for (const c of DATA.candidates) {
  if (!c.appliedJobId) continue;
  const job = DATA.jobs.find((j) => j.id === c.appliedJobId);
  if (!job) continue;
  n++;
  P(`insert into applications (id,job_id,candidate_id,stage,match_score,source,posting_type,`
    + `is_primary,applied_at,applied_on,resume_path) values (`
    + `${q('app_seed_' + c.id)},${q(c.appliedJobId)},${q(c.id)},${q(c.stage)},${num(c.matchScore)},`
    + `'portal',${q(job.type === 'Internship' ? 'internship' : 'job')},true,`
    + `now() - interval '14 days', current_date - 14, ${q(c.resumeFile)});`);
}
P(`-- ${n} primary applications`);

// Recruiter notes arrive as `recruiterComments` (or `comments`, from the
// enrichment block at :6392) once the page has fully loaded.
const comments = DATA.candidates.flatMap((c) =>
  (c.recruiterComments || c.comments || []).map((cm) => ({ cand: c.id, ...cm })));
if (comments.length) {
  P(`\n-- recruiter comments (${comments.length}) — moved off the candidate row so`);
  P(`-- RLS can keep one recruiter's notes from reaching another.`);
  for (const cm of comments) {
    P(`insert into candidate_comments (candidate_id,recruiter_id,tag,body) values (`
      + `${q(cm.cand)},'r1',${q(cm.tag)},${q(cm.text || cm.body || cm.comment)});`);
  }
}

P(`\n-- interviews (${DATA.interviews.length})`);
for (const iv of DATA.interviews) {
  P(`insert into interviews (id,candidate_id,job_id,application_id,type,scheduled_date,scheduled_time,`
    + `mode,status,interviewer,is_demo) values (`
    + `${q(iv.id)},${q(iv.candidateId)},${q(iv.jobId)},`
    + `(select id from applications where candidate_id=${q(iv.candidateId)} and job_id=${q(iv.jobId)} limit 1),`
    + `${q(iv.type)},${q(iv.date)},${q(iv.time)},${q(iv.mode)},${q(iv.status)},${q(iv.interviewer)},true);`);
}

const offerCands = DATA.candidates.filter((c) => c.stage === 'offer_extended' && c.appliedJobId);
P(`\n-- offers (${offerCands.length}) — the prototype had no offer records; it inferred`);
P(`-- them from the offer_extended stage. They become real rows (requirement 3).`);
for (const c of offerCands) {
  P(`insert into offers (id,application_id,candidate_id,job_id,ctc,status,extended_by) values (`
    + `${q('off_' + c.id)},${q('app_seed_' + c.id)},${q(c.id)},${q(c.appliedJobId)},`
    + `${num(c.expectedCtc)},'extended','r1');`);
}

P(`\n-- comm templates (${(DATA.whatsappTemplates || []).length})`);
for (const t of DATA.whatsappTemplates || []) {
  P(`insert into comm_templates (id,kind,name,body,verified) values (`
    + `${q('wa_' + t.key)},'whatsapp',${q(t.title)},'',true);`);
}

writeFileSync('supabase/migrations/0003_seed.sql', out.join('\n') + '\n');

const verified = DATA.candidates.filter((c) => c.emailVerified).length;
const gendered = DATA.candidates.filter((c) => c.gender).length;
console.log('wrote supabase/migrations/0003_seed.sql  (read from the running page)');
console.log(`  companies ${DATA.companies.length} · jobs ${DATA.jobs.length} · candidates ${DATA.candidates.length}`);
console.log(`  recruiters ${DATA.recruiters.length} · clients ${DATA.clients.length} · interviews ${DATA.interviews.length}`);
console.log(`  primary applications ${n} · offers ${offerCands.length} · recruiter comments ${comments.length}`);
console.log(`  enrichment captured: ${verified}/${DATA.candidates.length} email-verified, ${gendered} with gender`);
